<?php
 
declare(strict_types=1);
 
// First, include your main config to get BASE_URL and SITE_URL
require_once __DIR__ . '/app.php';

/**
 * QMAX Realty — Property Listings Data Configuration
 * Single source of truth for all property/listing data.
 *
 * Each entry represents a property with full details for individual listing pages.
 * Properties are indexed by slug for easy lookup.
 */

// Use the BASE_URL constant from your config
$base = BASE_URL;
$site = SITE_URL;

// For images, we need absolute URLs for SEO and social sharing
// Use SITE_URL for absolute URLs (required for og:image, JSON-LD, etc.)
// Use BASE_URL for relative paths within the application
 
return [
 
    // ─────────────────────────────────────────────────────────────────────────
    // LUXURY APARTMENTS
    // ─────────────────────────────────────────────────────────────────────────
 
    'sololaki-luxury-penthouse' => [
        'type'              => 'apartment',
        'slug'              => 'sololaki-luxury-penthouse',
        'title'             => 'Sololaki Luxury Penthouse with Panoramic City Views',
        'subtitle'          => 'Exclusive 3-bedroom penthouse in Tbilisi\'s most prestigious historic district',
        'property_type'     => 'Penthouse Apartment',
        'bedrooms'          => 3,
        'bathrooms'         => 2.5,
        'sqft'              => 2150,
        'price'             => 495000,
        'price_per_sqft'    => 230,
        'currency'          => 'USD',
        'location'          => 'Sololaki District, Tbilisi, Georgia',
        'neighborhood'      => 'Sololaki',
        'city'              => 'Tbilisi',
        'region'            => 'Tbilisi',
        'country'           => 'Georgia',
        'status'            => 'For Sale',
        'year_built'        => 2022,
        'floor'             => '7th floor (top floor)',
        'total_floors'      => 7,
        'property_size'     => '2150 sq ft (200 m²)',
        'lot_size'          => 'N/A',
        'parking'           => 'Secure underground parking included',
        'card_image'        => $base . 'img/placeholder_1.webp',
        'meta_description'  => 'Stunning 3-bedroom penthouse in Sololaki with panoramic Tbilisi views. Modern design, premium finishes, 2.5 baths, 2150 sq ft. Private terrace, parking included.',
        'short_description' => 'Experience luxury living in the heart of Tbilisi\'s historic Sololaki district. This top-floor penthouse offers breathtaking 360-degree views of the city, Old Town, and the Mtkvari River. Features premium European finishes, floor-to-ceiling windows, and a private terrace.',
        'full_description'  => '<p>Perched on the 7th floor of a newly constructed boutique building, this exquisite penthouse represents the pinnacle of urban living in Tbilisi. The <strong>Sololaki Luxury Penthouse</strong> combines historic neighborhood charm with contemporary design and unobstructed panoramic views.</p><p>The open-concept living area features <strong>floor-to-ceiling windows</strong> that flood the space with natural light while framing stunning views of Tbilisi\'s iconic skyline, including the Holy Trinity Cathedral and the Narikala Fortress. The European-designed kitchen boasts <strong>Gaggenau appliances</strong>, marble countertops, and custom cabinetry.</p><p>The master suite is a private sanctuary with a spacious walk-in closet, luxurious ensuite bathroom with a freestanding soaking tub and rainfall shower, and direct access to the <strong>private terrace</strong>. Two additional bedrooms offer generous space for family or guests.</p><p>This property includes <strong>secure underground parking</strong>, elevator access, and a dedicated storage unit. The building features a modern security system and video intercom.</p>',
        'features'          => [
            'Panoramic city and mountain views',
            'Private terrace (320 sq ft)',
            'Floor-to-ceiling windows',
            'Gaggenau kitchen appliances',
            'Marble countertops and backsplash',
            'Hardwood floors throughout',
            'Master suite with walk-in closet',
            'Freestanding soaking tub',
            'Rainfall shower in master bath',
            'Secure underground parking',
            'Elevator access',
            'Video intercom system',
            'Dedicated storage unit',
            'Central heating and cooling',
            'Built-in wine refrigerator',
            'Smart home system',
        ],
        'inclusions'        => [
            'Fully equipped kitchen with premium appliances',
            'Built-in wardrobes in all bedrooms',
            'Designer lighting fixtures',
            'Window treatments',
            'Parking space',
            'Storage unit',
        ],
        'exclusions'        => [
            'Furniture (available at additional cost)',
            'Utilities (electricity, water, gas)',
            'Maintenance fees (approximately 150 GEL/month)',
        ],
        'know_before_you_go' => [
            'Viewing by appointment only — contact us to schedule',
            'The building has 7 residential floors with elevator access',
            'Annual property tax: approximately 5,000 GEL',
            'Maintenance fee includes building cleaning and common area maintenance',
        ],
        'what_to_bring'     => [
            'ID/passport for viewing',
            'Pre-approval letter (if considering purchase)',
        ],
        'gallery'           => [
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
        ],
        'alt_texts'         => [
            'Sololaki penthouse panoramic view from terrace',
            'Living room with floor-to-ceiling windows',
            'Modern kitchen with marble countertops',
            'Master bedroom with city view',
            'Luxury bathroom with soaking tub',
            'Dining area with mountain vista',
        ],
        'floor_plan'        => $base . 'img/placeholder_2.webp',
        'virtual_tour'      => 'https://my.matterport.com/show/?m=example',
        'coords'            => [
            'lat' => 41.6938,
            'lng' => 44.8015,
        ],
        'nearby'            => [
            'Rustaveli Avenue (5 min walk)',
            'Freedom Square (10 min walk)',
            'Tbilisi Opera House (8 min walk)',
            'Mtatsminda Park (12 min walk)',
            'Sulphur Baths (15 min walk)',
            'Supermarkets (2 min walk)',
            'Cafes and restaurants (1-5 min walk)',
            'School (7 min walk)',
        ],
        'transport'         => [
            'Metro: Rustaveli Station (5 min walk)',
            'Bus stops at Liberty Square (10 min walk)',
            'Tbilisi International Airport (25 min drive)',
        ],
        'reviews'           => [
            [
                'text'     => 'Absolutely stunning property. The views from every window are incredible, and the quality of finishes is exceptional. The Sololaki location is unbeatable — quiet residential street but steps from everything. Highly recommend!',
                'author'   => 'Sarah J.',
                'platform' => 'Google Reviews',
                'rating'   => 5,
            ],
            [
                'text'     => 'We viewed several penthouses in Tbilisi, and this was by far the best value. The terrace alone is worth the investment. The team at QMAX made the purchase process seamless.',
                'author'   => 'David R.',
                'platform' => 'Google Reviews',
                'rating'   => 5,
            ],
            [
                'text'     => 'The attention to detail in this apartment is remarkable. From the hidden storage to the soundproofing, everything has been thought through. A true gem in the Sololaki district.',
                'author'   => 'Elena M.',
                'platform' => 'Google Reviews',
                'rating'   => 4.8,
            ],
        ],
        'agent'             => [
            'name'          => 'Nino Beridze',
            'title'         => 'Senior Property Specialist',
            'phone'         => '+995 599 123 456',
            'email'         => 'nino@qmaxrealty.ge',
            'image'         => $base . 'img/logo200.webp',
            'bio'           => 'Nino has 12+ years of experience in Tbilisi\'s luxury real estate market. She specializes in historic district properties and has facilitated over 100 successful transactions.',
        ],
        'faq'               => [
            [
                'question' => 'What is the maintenance fee?',
                'answer'   => 'The monthly maintenance fee is approximately 150 GEL and covers building cleaning, elevator maintenance, and common area upkeep.',
            ],
            [
                'question' => 'Can I rent this property as an Airbnb?',
                'answer'   => 'Yes, short-term rentals are allowed in the building. Many owners earn excellent returns due to the prime location and luxury amenities.',
            ],
            [
                'question' => 'Is this building pet-friendly?',
                'answer'   => 'Yes, the building welcomes pets. There is a small courtyard area for pet relief.',
            ],
            [
                'question' => 'How much is the property tax?',
                'answer'   => 'Annual property tax is approximately 5,000 GEL based on the current market value. This may change based on annual assessments.',
            ],
        ],
    ],
 
    'vera-garden-apartment' => [
        'type'              => 'apartment',
        'slug'              => 'vera-garden-apartment',
        'title'             => 'Vera Garden Apartment with Private Patio',
        'subtitle'          => 'Charming 2-bedroom garden apartment in Tbilisi\'s vibrant Vera district',
        'property_type'     => 'Garden Apartment',
        'bedrooms'          => 2,
        'bathrooms'         => 2,
        'sqft'              => 1450,
        'price'             => 325000,
        'price_per_sqft'    => 224,
        'currency'          => 'USD',
        'location'          => 'Vera District, Tbilisi, Georgia',
        'neighborhood'      => 'Vera',
        'city'              => 'Tbilisi',
        'region'            => 'Tbilisi',
        'country'           => 'Georgia',
        'status'            => 'For Sale',
        'year_built'        => 2018,
        'floor'             => 'Ground floor with garden access',
        'total_floors'      => 5,
        'property_size'     => '1450 sq ft (135 m²)',
        'lot_size'          => 'N/A',
        'parking'           => 'Street parking available (permit included)',
        'card_image'        => $base . 'img/placeholder_1.webp',
        'meta_description'  => 'Beautiful 2-bedroom garden apartment in Vera with private patio. Modern design, 2 baths, 1450 sq ft. Private outdoor space, quiet location, near Vake Park.',
        'short_description' => 'Discover this rare garden apartment in the heart of Vera — one of Tbilisi\'s most desirable neighborhoods. This ground-floor residence offers private outdoor space, contemporary interiors, and easy access to Vake Park and the city\'s best restaurants.',
        'full_description'  => '<p>Nestled on a quiet street in Tbilisi\'s prestigious Vera district, this garden apartment offers the perfect balance of city living and private outdoor space. The <strong>Vera Garden Apartment</strong> is a rare find in this sought-after location.</p><p>The interior features an open-plan living and dining area with <strong>floor-to-ceiling sliding doors</strong> that open onto a private paved patio and garden — ideal for al fresco dining or morning coffee. The kitchen is equipped with Bosch appliances, quartz countertops, and a breakfast bar.</p><p>Both bedrooms are generously sized with built-in wardrobes. The master bedroom includes an ensuite bathroom with a double vanity and a walk-in shower. The property is <strong>fully renovated</strong> with new plumbing, electrical, and high-quality finishing throughout.</p><p>Located within walking distance to Vake Park, Rustaveli Avenue, and numerous cafes, this property is ideal for those seeking a <strong>low-maintenance urban lifestyle</strong> with the luxury of private outdoor space.</p>',
        'features'          => [
            'Private patio and garden (430 sq ft)',
            'Floor-to-ceiling sliding doors',
            'Bosch kitchen appliances',
            'Quartz countertops',
            'Hardwood flooring',
            'Master suite with ensuite bath',
            'Built-in wardrobes',
            'Double-glazed windows',
            'New plumbing and electrical',
            'High ceilings (3.2 meters)',
            'Laundry room with washer/dryer',
            'Parking permit included',
            'Video intercom system',
            'Air conditioning units in all rooms',
        ],
        'inclusions'        => [
            'Kitchen appliances (Bosch)',
            'Washer and dryer',
            'Built-in wardrobes',
            'Window coverings',
            'Garden furniture (negotiable)',
        ],
        'exclusions'        => [
            'Some decorative items in photos',
            'Utilities',
            'Maintenance fee (50 GEL/month)',
        ],
        'know_before_you_go' => [
            'Ground floor apartment with easy access — suitable for those with mobility concerns',
            'Viewings available weekdays and weekends by appointment',
            'The property is in a residential building with 5 floors',
            'A no-shoe policy is observed in the building',
        ],
        'what_to_bring'     => [
            'ID/passport for viewing',
            'Fully charged phone for photos',
            'Questions for the agent about the building and area',
        ],
        'gallery'           => [
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
        ],
        'alt_texts'         => [
            'Private garden patio of Vera apartment',
            'Living room with access to outdoor space',
            'Modern kitchen with breakfast bar',
            'Master bedroom with built-in wardrobe',
            'Spacious bathroom with walk-in shower',
        ],
        'coords'            => [
            'lat' => 41.7098,
            'lng' => 44.7871,
        ],
        'nearby'            => [
            'Vake Park (3 min walk)',
            'Rustaveli Avenue (8 min walk)',
            'Tbilisi Zoo (5 min walk)',
            'Mziuri Park (7 min walk)',
            'Supermarket (2 min walk)',
            'Cafes and restaurants (2-5 min walk)',
            'Philharmonic Hall (10 min walk)',
        ],
        'transport'         => [
            'Metro: Technical University (12 min walk)',
            'Bus stops on Vera street (1 min walk)',
            'Tbilisi International Airport (30 min drive)',
        ],
        'reviews'           => [
            [
                'text'     => 'We love this apartment! The garden is a peaceful retreat in the middle of the city. The location is perfect — quiet but close to everything. Highly recommend for anyone wanting outdoor space in Tbilisi.',
                'author'   => 'Marta P.',
                'platform' => 'Google Reviews',
                'rating'   => 5,
            ],
        ],
        'agent'             => [
            'name'          => 'Giorgi Mekvabishvili',
            'title'         => 'Property Consultant',
            'phone'         => '+995 599 123 457',
            'email'         => 'giorgi@qmaxrealty.ge',
            'image'         => $base . 'img/logo200.webp',
            'bio'           => 'Giorgi specializes in residential properties in Tbilisi\'s sought-after Vera and Vake districts. He is known for his dedication to finding the perfect home for his clients.',
        ],
        'faq'               => [
            [
                'question' => 'Is the garden private?',
                'answer'   => 'Yes, the patio and garden area is exclusively for this apartment\'s use. It is fully fenced and secure.',
            ],
            [
                'question' => 'Can this property be rented out?',
                'answer'   => 'Yes, long-term rentals are permitted in the building. Short-term rentals (Airbnb) are not allowed by the building regulations.',
            ],
            [
                'question' => 'Are there maintenance fees?',
                'answer'   => 'The monthly maintenance fee is 50 GEL, which covers hallway cleaning, stairwell maintenance, and building insurance.',
            ],
        ],
    ],
 
    // ─────────────────────────────────────────────────────────────────────────
    // HOUSES
    // ─────────────────────────────────────────────────────────────────────────
 
    'saburtalo-family-house' => [
        'type'              => 'house',
        'slug'              => 'saburtalo-family-house',
        'title'             => 'Saburtalo Family House with Private Garden',
        'subtitle'          => 'Spacious 4-bedroom family home with large garden in Tbilisi\'s Saburtalo district',
        'property_type'     => 'Single-Family House',
        'bedrooms'          => 4,
        'bathrooms'         => 3,
        'sqft'              => 3200,
        'price'             => 650000,
        'price_per_sqft'    => 203,
        'currency'          => 'USD',
        'location'          => 'Saburtalo District, Tbilisi, Georgia',
        'neighborhood'      => 'Saburtalo',
        'city'              => 'Tbilisi',
        'region'            => 'Tbilisi',
        'country'           => 'Georgia',
        'status'            => 'For Sale',
        'year_built'        => 2005,
        'floor'             => 'Two-story house',
        'total_floors'      => 2,
        'property_size'     => '3200 sq ft (298 m²)',
        'lot_size'          => '0.25 acres (1,050 m²)',
        'parking'           => 'Driveway with 3 parking spaces',
        'card_image'        => $base . 'img/placeholder_1.webp',
        'meta_description'  => 'Beautiful 4-bedroom family house in Saburtalo with garden. 3200 sq ft, 3 baths, large yard, close to schools and shopping. Perfect for families.',
        'short_description' => 'This exceptional family home in Saburtalo offers spacious living with a large garden, perfect for children and entertaining. Four bedrooms, three bathrooms, and a modern kitchen make this the ideal home for growing families.',
        'full_description'  => '<p>Welcome to your family\'s dream home in <strong>Saburtalo</strong>, one of Tbilisi\'s most family-friendly neighborhoods. This beautiful two-story house offers 3,200 square feet of thoughtfully designed living space on a generous 1,050 m² plot.</p><p>The ground floor features an impressive <strong>open-plan living and dining area</strong> with 3.5-meter ceilings, a wood-burning fireplace, and large windows overlooking the garden. The modern kitchen includes a central island, premium appliances, and a walk-in pantry. A study/home office and a guest bedroom with full bathroom complete this level.</p><p>Upstairs, you\'ll find the <strong>spacious master suite</strong> with a walk-in closet, private balcony, and luxurious ensuite bathroom with a jacuzzi tub and separate shower. Two additional bedrooms share a family bathroom with dual vanities. The second-floor hallway features a convenient laundry area.</p><p>The <strong>private garden</strong> is a true highlight — perfectly landscaped with mature trees, a lawn for children to play, a patio for summer dining, and a vegetable garden. This property also includes a <strong>detached garage</strong> with workshop space.</p>',
        'features'          => [
            'Two-story family home',
            'Large private garden (1,050 m²)',
            'Open-plan living and dining',
            'Wood-burning fireplace',
            'Modern kitchen with island',
            'Walk-in pantry',
            'Master suite with jacuzzi and balcony',
            'Walk-in closet',
            'Home office/study',
            'Laundry room',
            'Detached garage with workshop',
            'Driveway parking for 3 cars',
            'Mature trees and landscaping',
            'Garden shed',
            'Central heating and cooling',
            'Security system',
            'High-speed internet ready',
        ],
        'inclusions'        => [
            'All kitchen appliances',
            'Washer and dryer',
            'Security system equipment',
            'Garden tools and shed',
            'Water irrigation system',
        ],
        'exclusions'        => [
            'Some furniture shown in photos',
            'Personal items',
            'Outdoor playset (negotiable)',
        ],
        'know_before_you_go' => [
            'House is family-friendly with a fully fenced garden',
            'Viewings by appointment only, preferred on weekdays',
            'The property has central heating and air conditioning',
            'Excellent school district — walking distance to several schools',
        ],
        'what_to_bring'     => [
            'ID/passport for viewing',
            'Comfortable shoes for garden tour',
            'Children are welcome at viewings',
        ],
        'gallery'           => [
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
        ],
        'alt_texts'         => [
            'Modern family house in Saburtalo',
            'Open-plan living room with fireplace',
            'Kitchen with central island',
            'Master bedroom with private balcony',
            'Family bathroom with dual vanities',
            'Dining area with garden view',
            'Private garden with mature trees',
        ],
        'coords'            => [
            'lat' => 41.7243,
            'lng' => 44.7761,
        ],
        'nearby'            => [
            'Schools (5 min walk)',
            'Shopping Center (8 min walk)',
            'Saburtalo Park (3 min walk)',
            'Hospital (10 min walk)',
            'Supermarket (4 min walk)',
            'Cafes and restaurants (5 min walk)',
            'Medical clinics (8 min walk)',
            'Sports complex (10 min walk)',
        ],
        'transport'         => [
            'Metro: Technical University (15 min walk)',
            'Bus stops nearby (2 min walk)',
            'Tbilisi International Airport (35 min drive)',
        ],
        'reviews'           => [
            [
                'text'     => 'We\'ve lived in this house for 8 years and have loved every moment. The garden is a paradise for children, and the location is perfect — quiet but close to everything. We\'re only selling because we\'re moving abroad.',
                'author'   => 'The Tsereteli Family',
                'platform' => 'Google Reviews',
                'rating'   => 5,
            ],
        ],
        'agent'             => [
            'name'          => 'Nino Beridze',
            'title'         => 'Senior Property Specialist',
            'phone'         => '+995 599 123 456',
            'email'         => 'nino@qmaxrealty.ge',
            'image'         => $base . 'img/logo200.webp',
            'bio'           => 'Nino has extensive experience with family homes in Saburtalo and surrounding areas. She understands the importance of finding the right home for growing families.',
        ],
        'faq'               => [
            [
                'question' => 'What schools are in the area?',
                'answer'   => 'The property is within walking distance of Tbilisi\'s top international and local schools, including the British-Georgian Academy and the European School.',
            ],
            [
                'question' => 'Is the garden fully fenced?',
                'answer'   => 'Yes, the garden is completely fenced with secure gates, making it safe for children and pets.',
            ],
            [
                'question' => 'What is the condition of the property?',
                'answer'   => 'The property is in excellent condition. The owners have maintained it meticulously with regular updates and renovations.',
            ],
        ],
    ],
 
    // ─────────────────────────────────────────────────────────────────────────
    // MODERN APARTMENTS
    // ─────────────────────────────────────────────────────────────────────────
 
    'vake-city-view-apartment' => [
        'type'              => 'apartment',
        'slug'              => 'vake-city-view-apartment',
        'title'             => 'Vake City View Apartment with Mountain Vistas',
        'subtitle'          => 'Contemporary 2-bedroom apartment with stunning views in Tbilisi\'s Vake district',
        'property_type'     => 'Luxury Apartment',
        'bedrooms'          => 2,
        'bathrooms'         => 2,
        'sqft'              => 1250,
        'price'             => 380000,
        'price_per_sqft'    => 304,
        'currency'          => 'USD',
        'location'          => 'Vake District, Tbilisi, Georgia',
        'neighborhood'      => 'Vake',
        'city'              => 'Tbilisi',
        'region'            => 'Tbilisi',
        'country'           => 'Georgia',
        'status'            => 'For Sale',
        'year_built'        => 2020,
        'floor'             => '12th floor',
        'total_floors'      => 14,
        'property_size'     => '1250 sq ft (116 m²)',
        'lot_size'          => 'N/A',
        'parking'           => 'Secure underground parking included',
        'card_image'        => $base . 'img/placeholder_1.webp',
        'meta_description'  => 'Luxury 2-bedroom apartment in Vake with mountain and city views. 1250 sq ft, 2 baths, modern finishes, parking included. Prime location.',
        'short_description' => 'Experience modern living at its finest in this contemporary Vake apartment. Floor-to-ceiling windows frame breathtaking views of the city and the Caucasus Mountains. This corner apartment offers privacy, natural light, and premium finishes.',
        'full_description'  => '<p>Located on the 12th floor of a premium residential tower in <strong>Vake</strong>, this apartment offers some of the best views in Tbilisi. The <strong>Vake City View Apartment</strong> combines luxury living with convenience and style.</p><p>The open floor plan creates a seamless flow between the living, dining, and kitchen areas. The <strong>modern kitchen</strong> features custom European cabinetry, quartz countertops, and high-end appliances. Floor-to-ceiling windows in every room provide panoramic views and abundant natural light.</p><p>The master bedroom is a private retreat with a walk-in closet and an ensuite bathroom featuring dual sinks, a large walk-in shower, and heated floors. The second bedroom includes a built-in wardrobe and access to the second bathroom.</p><p>Residents enjoy premium building amenities including a <strong>rooftop terrace</strong>, gym, and 24/7 concierge service. Located just steps from Vake Park and the city\'s best dining and shopping, this property offers the ultimate urban lifestyle.</p>',
        'features'          => [
            'Panoramic city and mountain views',
            '12th-floor corner apartment',
            'Floor-to-ceiling windows',
            'European kitchen cabinetry',
            'Quartz countertops',
            'Premium appliances',
            'Master suite with walk-in closet',
            'Heated floors in bathroom',
            'Walk-in shower',
            'Two spacious bedrooms',
            'Underground parking space',
            'Rooftop terrace access',
            'Fitness center',
            '24/7 concierge',
            'Video intercom',
            'Smart home technology',
            'High-speed fiber internet',
        ],
        'inclusions'        => [
            'All kitchen appliances (Miele)',
            'Washer/Dryer',
            'Built-in wardrobes',
            'Parking space',
            'Access to building amenities',
        ],
        'exclusions'        => [
            'Furniture',
            'Decorations shown in photos',
            'Utilities',
            'Maintenance fee (180 GEL/month)',
        ],
        'know_before_you_go' => [
            'Located on the 12th floor with two high-speed elevators',
            'Viewings available daily from 10:00 AM to 6:00 PM',
            'The building has on-site security and CCTV',
            'Pet-friendly building with designated pet areas',
        ],
        'what_to_bring'     => [
            'ID/passport',
            'Camera to capture the views',
            'Questions about the building and neighborhood',
        ],
        'gallery'           => [
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
        ],
        'alt_texts'         => [
            'Vake apartment living room with mountain view',
            'Modern kitchen with city backdrop',
            'Master bedroom with walk-in closet',
            'Bathroom with heated floors and walk-in shower',
            'View of Tbilisi from the 12th floor',
        ],
        'coords'            => [
            'lat' => 41.7102,
            'lng' => 44.7829,
        ],
        'nearby'            => [
            'Vake Park (2 min walk)',
            'Rustaveli Avenue (5 min walk)',
            'Tbilisi Zoo (3 min walk)',
            'Philharmonic Hall (7 min walk)',
            'Supermarket (1 min walk)',
            'Cafes and restaurants (1-3 min walk)',
            'Movie theater (8 min walk)',
            'Sport center (5 min walk)',
        ],
        'transport'         => [
            'Metro: Rustaveli (5 min walk)',
            'Multiple bus lines (1 min walk)',
            'Tbilisi International Airport (25 min drive)',
        ],
        'reviews'           => [
            [
                'text'     => 'This apartment is incredible. The views alone are worth it, but the quality of construction and finishes is outstanding. The location is unbeatable — everything is within walking distance. We\'re thrilled with our purchase.',
                'author'   => 'Anna & Thomas N.',
                'platform' => 'Google Reviews',
                'rating'   => 5,
            ],
        ],
        'agent'             => [
            'name'          => 'Giorgi Mekvabishvili',
            'title'         => 'Property Consultant',
            'phone'         => '+995 599 123 457',
            'email'         => 'giorgi@qmaxrealty.ge',
            'image'         => $base . 'img/logo200.webp',
            'bio'           => 'Giorgi specializes in luxury apartments in Vake and knows the local market intimately. He can help you find the perfect urban home in Tbilisi\'s most desirable neighborhoods.',
        ],
        'faq'               => [
            [
                'question' => 'Is the building wheelchair accessible?',
                'answer'   => 'Yes, the building has wheelchair-accessible entrances and elevators.',
            ],
            [
                'question' => 'What is the policy on short-term rentals?',
                'answer'   => 'Short-term rentals are permitted with board approval. The building has a 30-day minimum rental period requirement.',
            ],
            [
                'question' => 'How much are the monthly maintenance fees?',
                'answer'   => 'The monthly maintenance fee is 180 GEL and covers building management, elevator maintenance, common area cleaning, and utilities for common areas.',
            ],
        ],
    ],
 
    // ─────────────────────────────────────────────────────────────────────────
    // RENTAL PROPERTIES
    // ─────────────────────────────────────────────────────────────────────────
 
    'old-town-charming-studio' => [
        'type'              => 'apartment',
        'slug'              => 'old-town-charming-studio',
        'title'             => 'Old Town Charming Studio with Balcony',
        'subtitle'          => 'Cozy studio apartment in Tbilisi\'s historic Old Town — perfect for short-term stays',
        'property_type'     => 'Studio Apartment',
        'bedrooms'          => 0, // Studio
        'bathrooms'         => 1,
        'sqft'              => 480,
        'price'             => 650,
        'price_per_month'   => 650,
        'currency'          => 'USD',
        'location'          => 'Old Town, Tbilisi, Georgia',
        'neighborhood'      => 'Old Town',
        'city'              => 'Tbilisi',
        'region'            => 'Tbilisi',
        'country'           => 'Georgia',
        'status'            => 'For Rent',
        'year_built'        => 1860,
        'renovated'         => 2019,
        'floor'             => '3rd floor',
        'total_floors'      => 4,
        'property_size'     => '480 sq ft (45 m²)',
        'lot_size'          => 'N/A',
        'parking'           => 'Street parking available (pay per hour)',
        'card_image'        => $base . 'img/placeholder_1.webp',
        'meta_description'  => 'Charming studio in Tbilisi Old Town with balcony. Fully renovated, central location, 480 sq ft. Available for short-term rental. 650 USD/month.',
        'short_description' => 'Experience the authentic charm of Tbilisi\'s Old Town in this beautifully renovated studio. Featuring original architectural details, a small balcony with views of the historic district, and modern amenities, this property is perfect for those seeking a genuine Tbilisi experience.',
        'full_description'  => '<p>Nestled in the heart of <strong>Tbilisi\'s Old Town</strong>, this charming studio apartment offers a perfect blend of historic character and modern comfort. The property has been lovingly renovated to preserve its 19th-century charm while incorporating contemporary conveniences.</p><p>The studio features <strong>high ceilings</strong>, original wooden floors, and a small balcony overlooking the historic neighborhood. The layout is smartly designed with a sleeping area, cozy living space, and a compact but fully equipped kitchen with a dining area.</p><p>The bathroom is modern with a rainfall shower, heated towel rack, and high-quality fixtures. The property benefits from <strong>central heating</strong>, air conditioning, and high-speed internet.</p><p>Located within walking distance of <strong>Narikala Fortress, Sulphur Baths, and Freedom Square</strong>, this studio is ideal for those who want to experience the authentic Tbilisi lifestyle. Short-term rental is permitted, making it a great investment opportunity.</p>',
        'features'          => [
            'Original architectural details',
            'Small balcony with Old Town views',
            'High ceilings (3.5 meters)',
            'Original wooden floors',
            'Fully renovated in 2019',
            'Modern kitchen with induction cooktop',
            'Rainfall shower',
            'Heated towel rack',
            'Central heating',
            'Air conditioning (cooling/heating)',
            'High-speed fiber internet',
            'Smart TV',
            'Soundproof windows',
            'Coded entry door',
        ],
        'inclusions'        => [
            'Fully furnished with quality furniture',
            'Kitchen appliances (refrigerator, induction cooktop, microwave)',
            'Linens and towels',
            'Internet and utilities included',
        ],
        'exclusions'        => [
            'None — utilities included in rent',
        ],
        'know_before_you_go' => [
            '3rd floor walk-up with no elevator',
            'The building is historic and has been maintained to preserve its character',
            'Quiet hours observed from 11 PM to 8 AM (building regulation)',
            'Short-term rental (1-12 months) or longer-term available',
        ],
        'what_to_bring'     => [
            'Personal belongings',
            'Comfortable walking shoes for exploring Old Town',
        ],
        'gallery'           => [
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
        ],
        'alt_texts'         => [
            'Cozy studio apartment in Tbilisi Old Town',
            'Modern kitchen and dining area',
            'Sleeping area with original features',
            'Modern bathroom with rainfall shower',
            'Old Town view from the balcony',
        ],
        'coords'            => [
            'lat' => 41.6917,
            'lng' => 44.8075,
        ],
        'nearby'            => [
            'Narikala Fortress (5 min walk)',
            'Sulphur Baths (4 min walk)',
            'Freedom Square (8 min walk)',
            'Betlemi Street (1 min walk)',
            'Shardeni Street (2 min walk)',
            'Restaurants and cafes (1-2 min walk)',
            'Convenience store (1 min walk)',
            'Bambis Rigi Park (6 min walk)',
        ],
        'transport'         => [
            'Metro: Liberty Square (8 min walk)',
            'Cable car to Narikala (5 min walk)',
            'Bus stops nearby (2 min walk)',
            'Tbilisi International Airport (20 min drive)',
        ],
        'reviews'           => [
            [
                'text'     => 'We stayed here for two weeks and absolutely loved it. The location is perfect — right in the heart of Old Town with everything within walking distance. The studio is beautifully decorated and the balcony is a lovely spot for morning coffee.',
                'author'   => 'Jessica L.',
                'platform' => 'Airbnb',
                'rating'   => 5,
            ],
            [
                'text'     => 'Perfect little studio for a solo traveler or couple. The renovation is impressive and the owner is very responsive. We\'ll definitely be booking again on our next visit to Tbilisi.',
                'author'   => 'Markus H.',
                'platform' => 'Booking.com',
                'rating'   => 4.9,
            ],
        ],
        'agent'             => [
            'name'          => 'Nino Beridze',
            'title'         => 'Senior Property Specialist',
            'phone'         => '+995 599 123 456',
            'email'         => 'nino@qmaxrealty.ge',
            'image'         => $base . 'img/logo200.webp',
            'bio'           => 'Nino manages the rental portfolio for QMAX Realty and knows the Old Town market exceptionally well.',
        ],
        'faq'               => [
            [
                'question' => 'Is the rent all-inclusive?',
                'answer'   => 'Yes, the rent includes all utilities including electricity, water, heating, and internet.',
            ],
            [
                'question' => 'Is there an elevator?',
                'answer'   => 'No, this is a 3rd floor walk-up. Please note for those with mobility concerns.',
            ],
            [
                'question' => 'What is the minimum rental period?',
                'answer'   => 'The minimum rental period is 1 month. Longer-term rentals are preferred.',
            ],
        ],
    ],
 
    // ─────────────────────────────────────────────────────────────────────────
    // LUXURY HOUSES
    // ─────────────────────────────────────────────────────────────────────────
 
    'tbilisi-sea-luxury-villa' => [
        'type'              => 'house',
        'slug'              => 'tbilisi-sea-luxury-villa',
        'title'             => 'Tbilisi Sea Luxury Villa with Private Beach Access',
        'subtitle'          => 'Spectacular 5-bedroom villa with private beach and pool overlooking Tbilisi Sea',
        'property_type'     => 'Luxury Villa',
        'bedrooms'          => 5,
        'bathrooms'         => 4.5,
        'sqft'              => 4500,
        'price'             => 1250000,
        'price_per_sqft'    => 278,
        'currency'          => 'USD',
        'location'          => 'Tbilisi Sea, Tbilisi, Georgia',
        'neighborhood'      => 'Tbilisi Sea',
        'city'              => 'Tbilisi',
        'region'            => 'Tbilisi',
        'country'           => 'Georgia',
        'status'            => 'For Sale',
        'year_built'        => 2021,
        'floor'             => 'Two-story with basement',
        'total_floors'      => 3,
        'property_size'     => '4500 sq ft (418 m²)',
        'lot_size'          => '0.5 acres (2,000 m²)',
        'parking'           => 'Garage for 4 cars + driveway for 6 cars',
        'card_image'        => $base . 'img/placeholder_1.webp',
        'meta_description'  => 'Luxury villa at Tbilisi Sea with private beach and pool. 5 bedrooms, 4500 sq ft, panoramic views. Private beach access, huge garden. Price 1,250,000 USD.',
        'short_description' => 'Experience the pinnacle of lakeside living at this stunning villa overlooking Tbilisi Sea. This meticulously designed property features a private beach, infinity pool, expansive terraces, and breathtaking water views. Perfect for those seeking luxury and privacy.',
        'full_description'  => '<p>Perched on the shores of <strong>Tbilisi Sea</strong>, this exceptional villa represents the ultimate in Georgian luxury real estate. The <strong>Tbilisi Sea Luxury Villa</strong> offers an unparalleled lifestyle combining elegance, comfort, and spectacular natural surroundings.</p><p>The main level features a <strong>grand living area</strong> with floor-to-ceiling windows overlooking the lake, a fireplace, and direct access to expansive terraces. The gourmet kitchen is a chef\'s dream with high-end appliances, a large island, and a walk-in pantry. Formal dining and comfortable family areas complete this level.</p><p>All five bedrooms are generously proportioned. The <strong>master suite</strong> is a private sanctuary with panoramic lake views, private terrace, large walk-in closet, and a spa-inspired bathroom with a soaking tub and walk-in shower.</p><p>Outdoors, the property features a <strong>private beach</strong>, infinity swimming pool, outdoor kitchen, lush gardens, and several terraces perfect for entertaining. A separate guest house provides additional accommodation.</p>',
        'features'          => [
            'Private beach on Tbilisi Sea',
            'Infinity swimming pool',
            'Lake and mountain views',
            '5 bedrooms, 4.5 baths',
            'Master suite with lake view',
            'Gourmet kitchen with high-end appliances',
            'Walk-in pantry',
            'Expansive terraces and balconies',
            'Fireplace in living room',
            'Separate guest house',
            'Garage for 4 cars',
            'Landscaped gardens',
            'Outdoor kitchen',
            'Security system',
            'Underfloor heating',
            'Smart home system',
            'Wine cellar in basement',
            'Home theater room',
        ],
        'inclusions'        => [
            'All kitchen appliances (Miele)',
            'Washer and dryer',
            'Smart home system equipment',
            'Outdoor furniture',
            'Pool maintenance equipment',
        ],
        'exclusions'        => [
            'Some indoor furniture',
            'Artwork and decorations',
        ],
        'know_before_you_go' => [
            'Private showings by appointment only',
            'The property is gated with 24/7 security',
            'Tbilisi Sea is a popular leisure destination with water sports and dining',
            'The villa is approximately 15 minutes from central Tbilisi',
        ],
        'what_to_bring'     => [
            'ID/passport',
            'Pre-approval for financing if applicable',
            'Questions about the property and area',
        ],
        'gallery'           => [
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
            $base . 'img/placeholder_1.webp',
            $base . 'img/placeholder_2.webp',
        ],
        'alt_texts'         => [
            'Luxury villa overlooking Tbilisi Sea',
            'Infinity pool with lake view',
            'Modern kitchen with lake vistas',
            'Master bedroom with private balcony',
            'Living room with panoramic windows',
            'Private beach area',
            'Landscaped garden and outdoor dining',
        ],
        'coords'            => [
            'lat' => 41.7348,
            'lng' => 44.7652,
        ],
        'nearby'            => [
            'Tbilisi Sea waterfront (0 min walk)',
            'Restaurants and cafes (5 min walk)',
            'Water sports facilities (3 min walk)',
            'Walking and cycling paths (1 min walk)',
            'Park area (2 min walk)',
            'Central Tbilisi (15 min drive)',
            'Tbilisi International Airport (20 min drive)',
        ],
        'transport'         => [
            'Private transport recommended',
            'Tbilisi International Airport (20 min drive)',
            'Central Tbilisi (15 min drive)',
            'Public transport nearby (bus stop 5 min walk)',
        ],
        'reviews'           => [
            [
                'text'     => 'One of the most beautiful properties we\'ve ever seen. The attention to detail in the construction and design is remarkable. The lake view from every room is breathtaking, and the private beach is a rare luxury in Tbilisi. Highly recommend!',
                'author'   => 'International Luxury Living Magazine',
                'platform' => 'Feature Review',
                'rating'   => 5,
            ],
            [
                'text'     => 'The perfect family home with spectacular views. We\'ve been here twice for viewings and are amazed by the quality. The builders spared no expense, and the location offers the perfect balance of privacy and convenience.',
                'author'   => 'Maria & Dimitri K.',
                'platform' => 'Google Reviews',
                'rating'   => 5,
            ],
        ],
        'agent'             => [
            'name'          => 'Nino Beridze',
            'title'         => 'Senior Property Specialist',
            'phone'         => '+995 599 123 456',
            'email'         => 'nino@qmaxrealty.ge',
            'image'         => $base . 'img/logo200.webp',
            'bio'           => 'Nino is our luxury property specialist with over 15 years of experience in high-end real estate in Georgia. She has handled numerous international transactions and can guide you through the entire process.',
        ],
        'faq'               => [
            [
                'question' => 'What is the beach situation at Tbilisi Sea?',
                'answer'   => 'The property has a private beach area exclusively for residents. The water is clean and safe for swimming during the summer months.',
            ],
            [
                'question' => 'Is the property in a gated community?',
                'answer'   => 'Yes, the villa is part of an exclusive gated community with 24/7 security, CCTV, and private road maintenance.',
            ],
            [
                'question' => 'What is the annual maintenance fee?',
                'answer'   => 'The annual maintenance fee is approximately $5,000 USD and covers security, common area maintenance, road upkeep, and security.',
            ],
            [
                'question' => 'Can foreign nationals purchase this property?',
                'answer'   => 'Yes, foreign nationals can purchase property in Georgia. We can connect you with our legal partners for assistance with the purchase process.',
            ],
        ],
    ],
];